grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
    search_param_grid:
    
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: 20
      n_estimators: 20
      min_samples_split: 2
      min_samples_leaf: 2
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      n_estimators:
      - 50
      - 100
      - 200
      min_samples_split:
      - 2
      - 5
      - 10
      min_samples_leaf:
      - 1
      - 2
      - 4